# Generated by Django 2.2 on 2022-08-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_id_anne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='id_anne',
        ),
    ]
